// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/vehicle-routing": {
    params: {};
  };
  "/benchmarks": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/vehicle-routing" | "/benchmarks";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/vehicle-routing/route.tsx": {
    id: "routes/vehicle-routing/route";
    page: "/vehicle-routing";
  };
  "./routes/benchmarks/route.tsx": {
    id: "routes/benchmarks/route";
    page: "/benchmarks";
  };
};