// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/vehicle-routing": {
    params: {};
  };
  "/benchmarks": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jobs" | "/vehicle-routing" | "/benchmarks";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/jobs/route.tsx": {
    id: "routes/jobs/route";
    page: "/jobs";
  };
  "./routes/vehicle-routing/route.tsx": {
    id: "routes/vehicle-routing/route";
    page: "/vehicle-routing";
  };
  "./routes/benchmarks/route.tsx": {
    id: "routes/benchmarks/route";
    page: "/benchmarks";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/./routes/home.tsx");
  "routes/jobs/route": typeof import("./src/./routes/jobs/route.tsx");
  "routes/vehicle-routing/route": typeof import("./src/./routes/vehicle-routing/route.tsx");
  "routes/benchmarks/route": typeof import("./src/./routes/benchmarks/route.tsx");
};